### ISSUE TITLE
Next bug

### ISSUE THREAD

**Issue by tannn** [tannn/TriviaTime#321]
The next command appears to not be functioning for registered users, telling them they are not the current streak holder.

**Comment by tannn** [comment]
It's currently working, but I had reports from two individuals that it wasn't working.

**Comment by tannn** [comment]
Related: 

http://pastebin.com/Y0XExUVC

**Comment by toagac** [comment]
The error occurs if someone presents the correct answer between when someone uses next and the following question even though the question has already ended from my observation

**Comment by tannn** [comment]
Marking as fixed for now.
